### ISSUE TITLE
File Queue

### ISSUE THREAD

**Issue by Taar** [pytube/antioch#11]
Queue for processing json/video files in the source folder.

When the queue is started it'll insert an item into the queue for each json file in the source folder. Then it'll start watchdog which will add new items to the queue when new json files are added to the source folder.

If the process is killed (for whatever reason) our state will what's still in the source folder.

The queue requires a worker function to run for each item in the queue.

Libraries: [Queue](https://docs.python.org/3.5/library/queue.html), [watchdog](pythonhosted.org/watchdog/api.html)

**Comment by blakev** [comment]
Completed in #16
